spring.datasource.url=jdbc:postgresql://localhost:5432/bookingdetailsservice
spring.datasource.username=postgres
spring.datasource.password=akilan24
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
spring.main.allow-circular-references: true
server.port=8084
spring.application.name=BOOKINGDETAILS-SERVICE
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.health.circuitbreakers.enabled=true
endpoint.health.show-details=always

resilience4j.circuitbreaker.instances.Room.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.Room.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.Room.failureRateThreshold=50
resilience4j.circuitbreaker.instances.Room.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.Room.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.Room.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.Room.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.Room.slidingWindowSize=10
resilience4j.circuitbreaker.instances.Room.slidingWindowType=COUNT_BASED
