#JPA properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
spring.main.allow-circular-references: true
server.port=8003

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/Hotel
spring.datasource.username=postgres
spring.datasource.password=akilan24
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#H2 database
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:hma
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=hma
#spring.datasource.password=hma
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.defer-datasource-initialization=true

#eureka client
spring.application.name=ROOMDETAILS-SERVICE
spring.config.import=optional:configserver:http://localhost:8888
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:8761/eureka/
eureka.instance.hostname=localhost
spring.cloud.discovery.enabled=true
spring.zipkin.base-url=http://127.0.0.1:9411/

#actuator
management.endpoints.web.exposure.include=*
#info
#management.info.env.enabled=true
#info.app.name=Spring boot
#info.app.description=user service 
#info.app.version=1.0.0
##health
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
##shutdown
#management.endpoint.shutdown.enabled=true

# Circuit Breaker configuration
resilience4j.circuitbreaker.instances.ROOMDETAILS-SERVICE.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.ROOMDETAILS-SERVICE.failureRateThreshold=50
resilience4j.circuitbreaker.instances.ROOMDETAILS-SERVICE.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.ROOMDETAILS-SERVICE.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.ROOMDETAILS-SERVICE.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.ROOMDETAILS-SERVICE.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.ROOMDETAILS-SERVICE.slidingWindowSize=10
resilience4j.circuitbreaker.instances.ROOMDETAILS-SERVICE.slidingWindowType=COUNT_BASED

# Retry configuration
resilience4j.retry.instance.ROOMDETAILS-SERVICE.registerHealthIndicator=true
resilience4j.retry.instances.ROOMDETAILS-SERVICE.maxRetryAttempts=5
resilience4j.retry.instances.ROOMDETAILS-SERVICE.waitDuration=2s
